#!/bin/bash

cgreen=$(echo -e "\e[32m")
cred=$(echo -e "\e[91m")
cunder=$(echo -e "\e[4m")
creset=$(echo -e "\e[0m")

please_wait(){

local pid=$1
local task=$2
local onfailkill=$3
local delay=0.5

while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
  printf "\r[    ] $task"
  sleep $delay
  printf "\r[ .  ]"
  sleep $delay
  printf "\r[ .. ]"
  sleep $delay
  printf "\r[  . ]" 
  sleep $delay
done

if wait $pid; then
  printf "\r[ ${cgreen}OK${creset} ] $task $rc \n"
else
  printf "\r[${cred}FAIL${creset}] $task $rc \n"
fi
}

move_and_echo() {
  echo -ne "\E[${1};${2}H""$3" 
}
