#!/bin/bash

cgreen=$(echo -e "\e[32m")
creset=$(echo -e "\e[0m")

please_wait(){

local pid=$1
local delay=0.75
local task=$2

while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
  printf "\r[    ] $task"
  sleep $delay
  printf "\r[ .  ]"
  sleep $delay
  printf "\r[ .. ]"
  sleep $delay
  printf "\r[  . ]" 
  sleep $delay
done
printf "\r[ ${cgreen}OK${creset} ] $task \n"

}

move_and_echo() {
  echo -ne "\E[${1};${2}H""$3" 
}
