#!/bin/bash

####################################################################################
# fast_network: customize the network configuration for the fast infrastructure
#
# Author: Hans Then <hans.then@clustervision.com>
# 
# This file does the following
# 1. it takes the IP address of eth0
# 2. assigns it to the docker0 bridge
# 3. adds eth0 do the docker0 bridge
# 4. creates an alias docker0:0 to be used as gateway for the container
# 5. adds a default route to the controller

IP=$(ip addr show dev eth0 scope global | grep inet | awk -F' ' '{print $2}')
if [ -z "$IP" ]; then
echo "No IP found on eth0, assume we have been here before. DRY!"
return
fi

if ! ifconfig docker0 > /dev/null 2>&1; then
echo "Interface docker0 not found. Please start docker first."
exit 1
fi

GW=$(ip addr show dev docker0 scope global | grep inet | awk -F' ' '{print $2}')

IP3_4=$(echo $IP | awk -F'/' '{print $1}' | awk -F'.' '{print $2"."$4}')
IP3_4_GW=$(echo $IP | awk -F'/' '{print $1}' | awk -F'.' '{print $2+127"."$4}')

# setup two interfaces docker0 with the gateway interface and docker0:0 in the bridge
ip addr flush dev docker0
ip addr add 172.17.${IP3_4_GW}/16 dev docker0
ifconfig docker0:0 ${IP}

# remove the ip addres from eth0
ip addr flush dev eth0

# add the eth0 device to the docker0 bridge
brctl addif docker0 eth0

# setup the route to the controller
route add default gw controller

